### PR TITLE
AddKruskal'sAlgorithm

### PR DESCRIPTION
**Pull request by atingarg1406**
Program of Kruskal's Algorithm in C++

### CODE REVIEW

**Review by Kanhakhatri065 — CHANGES_REQUESTED** [review]
Use comments to properly explain your code.

**Comment by shubhamnag14** [comment]
can i contribute this algorithm

**Comment by Kanhakhatri065** [comment]
Please make the changes requested.

**Comment by shubhamnag14** [comment]
okay..i will do the job

**Pull request merged**
