### PR TITLE
palindrome number check

### PR DESCRIPTION
**Pull request by import-prospero**
python program to check if number is palindrome or not ...please merge it..
for hacktoberfest

### CODE REVIEW

**Comment by zafar-hussain** [comment]
hi @import-prospero 

the task is to:
 "Build a function that checks weather a given number is a palindrome or not without using a strings. Implement it using any language.

For example:
input: 12321
output: true"

but your code uses strings, hence not satisfying the requirement.

you need to solve it only using numbers, not strings

**Comment by import-prospero** [comment]
updated pal.py...to check palindrome integer without using strings...please merge it for hacktoberfest

**Review by zafar-hussain — APPROVED** [review]

**Comment by zafar-hussain** [comment]
nice one @import-prospero 
welldone

**Review by zafar-hussain — APPROVED** [review]

**Comment by import-prospero** [comment]
i dont know it wasnt counted in my hacktoberfest PRs....please add the hacktoberfest-accepted label...

**Comment by zafar-hussain** [comment]
@ephremdeme  please merge this PR, and add Hacktoberfest label,
thanks

**Comment by import-prospero** [comment]
how much more time...please add the label..

**Comment by zafar-hussain** [comment]
@Kanhakhatri065 , please if you can merge the PR and Add the Label
thanks

**Pull request merged**
