### PR TITLE
Adds Pascal Triangle in python

### PR DESCRIPTION
**Pull request by Cybertron-Avneesh**
PR for issue #206 

Wrote code in python to print pascal triangle.

### CODE REVIEW

**Comment by ephremdeme** [comment]
The folder name is Pascal not Pascal-Triangle. change it.

**Comment by Cybertron-Avneesh** [comment]
> The folder name is Pascal not Pascal-Triangle. change it.

Yeah Sure.

**Comment by Cybertron-Avneesh** [comment]
> The folder name is Pascal not Pascal-Triangle. change it.

Did the changes. Please review.

**Comment by ephremdeme** [comment]
@all-contributors please add @Cybertron-Avneesh  for code

**Pull request merged**
