### PR TITLE
All contributors/add pankajcoder1

### PR DESCRIPTION
**Pull request by Pankajcoder1**
Update readme file for previous pull request.
Please accept it.

### CODE REVIEW

**Review by ephremdeme — COMMENTED** [review]
Why did you delete the file?

**Comment by Pankajcoder1** [comment]
> Why did you delete the file?

That was not best appraoch so I deleted but i am looking for best approach for that algorithm.

**Comment by Kanhakhatri065** [comment]
Add this naive approach and add the efficient one also.

**Comment by Kanhakhatri065** [comment]
@Pankajcoder1 rebase to previous commits and do not tweak other files. So, I'm gonna close this one. Create a PR with your implementations.

**Pull request closed without merging**
