### PR TITLE
adding fibonnaci series in java.

### PR DESCRIPTION
**Pull request by krishnmohan19**

### CODE REVIEW

**Comment by ephremdeme** [comment]
Move the code to Mathematics folder  and re-structure accordingly

**Comment by krishnmohan19** [comment]
sure @ephremdeme

**Comment by krishnmohan19** [comment]
hey @ephremdeme  ,i have made changes in my pr .plz review it

**Comment by Kanhakhatri065** [comment]
You can implement it in any language except the one in which it is already implemented. As someone has implemented it in JAVA. So, I'm gonna close this PR.

**Pull request closed without merging**
