### PR TITLE
Fibonnaci series in Java

### PR DESCRIPTION
**Pull request by Prash2002**

### CODE REVIEW

**Comment by ephremdeme** [comment]
Move the code to Mathematics folder  and re-structure accordingly

**Comment by Prash2002** [comment]
@ephremdeme , done.

**Comment by Kanhakhatri065** [comment]
Looks good to me. I'm gonna merge it now.

**Comment by Prash2002** [comment]
> Looks good to me. I'm gonna merge it now.

Thanks :)

**Pull request merged**
