### PR TITLE
Binary Search

### PR DESCRIPTION
**Pull request by amanjhurani**
Binary Search using Python

### CODE REVIEW

**Comment by amanjhurani** [comment]
Linear Search using Python

**Comment by ephremdeme** [comment]
@all-contributors please add  amanjhurani  for ideas

**Comment by ephremdeme** [comment]
@all-contributors please add  #4PRITI24  for code

**Comment by ephremdeme** [comment]
@all-contributors please add PRITI24  for code

**Comment by ephremdeme** [comment]
@all-contributors please add  tusharkashyap63  for design

**Comment by ephremdeme** [comment]
@all-contributors please add TastySalad for code

**Pull request merged**
