### PR TITLE
Fibonacci series (recursive solution)

### PR DESCRIPTION
**Pull request by gokulkannan7**
fibonacci.cpp implemented in c++ and added #15

### CODE REVIEW

**Comment by ephremdeme** [comment]
Move the code to Mathematics folder  and re-structure accordingly

**Comment by gokulkannan7** [comment]
@ephremdeme  shall I create one folder called mathematics inside the problems folder and then move this file there?

**Comment by ephremdeme** [comment]
There is already a Mathematics folder

**Comment by gokulkannan7** [comment]
@ephremdeme  I have added into the mathematics folder, pls check

**Pull request closed without merging**
