### PR TITLE
Added firstDuplicate(cpp) in problems

### PR DESCRIPTION
**Pull request by ankitaugale23**

### CODE REVIEW

**Comment by ankitaugale23** [comment]
Hello, after this PR on my Hactoberfest profile it is showing that this repository is invalid to consider my PR in the contribution for Hactoberfest. Is there any issue? @Kanhakhatri065

**Comment by Kanhakhatri065** [comment]
No, there isn't.

**Comment by Kanhakhatri065** [comment]
hacktoberfest-accepted

**Comment by ankitaugale23** [comment]
I think you have to add a label to my PR "Hactoberfest-accepted" that's what was written in the new rules. Kindly look into it. @Kanhakhatri065

**Comment by ankitaugale23** [comment]
It is resolved thank you so much! @Kanhakhatri065

**Pull request merged**
