### PR TITLE
Remove duplicates from a list

### PR DESCRIPTION
**Pull request by phistav**
Remove duplicates.

Note: please add hacktoberfest-accepted to the PR.

### CODE REVIEW

**Comment by phistav** [comment]
@Kanhakhatri065 @zafar-hussain Could you please review this request?

**Comment by zafar-hussain** [comment]
looks good, well-done @phistav 

another idea, what if we convert the given list into a set  and then into a list, would that work?

**Review by zafar-hussain — APPROVED** [review]

**Comment by zafar-hussain** [comment]
@ephremdeme, please merge this PR

cheers

**Comment by phistav** [comment]
> looks good, well-done @phistav
> 
> another idea, what if we convert the given list into a set and then into a list, would that work?

sure that is another way that would work

**Comment by phistav** [comment]
@zafar-hussain could you please add hacktoberfest-accepted to the PR?

**Comment by zafar-hussain** [comment]
@Kanhakhatri065, please if you can merge and label this PR
thanks

**Pull request merged**
