### PR TITLE
Pascal Triangle

### PR DESCRIPTION
**Pull request by khare-agraj**
I have done the implementation with comments

### CODE REVIEW

**Comment by Kanhakhatri065** [comment]
This one looks like a right-angled triangle. Can you create a equilateral version?

**Comment by khare-agraj** [comment]
sure, I can pretty print the pascal triangle

**Comment by khare-agraj** [comment]
Kindly check my new PR "Pascal Triangle with Pretty Print"

**Comment by Kanhakhatri065** [comment]
I have merged it.

**Pull request closed without merging**
