### PR TITLE
Adding Pascal Triangle in PHP

### PR DESCRIPTION
**Pull request by juanmagutierrez**
PR for issue #206

Wrote code in PHP to print pascal triangle.

### CODE REVIEW

**Comment by Kanhakhatri065** [comment]
Looks good to me. I'm gonna merge it now.

**Comment by Kanhakhatri065** [comment]
@all-contributors please add @juanmagutierrez

**Comment by Kanhakhatri065** [comment]
@all-contributors please add @juanmagutierrez for code, ideas, design.

**Comment by juanmagutierrez** [comment]
@Kanhakhatri065 can you add "hacktoberfest-accepted" label to the PR ? thanks!

**Comment by juanmagutierrez** [comment]
> Looks good to me. I'm gonna merge it now.

@Kanhakhatri065 can you add "hacktoberfest-accepted" label to the PR ? thanks!

**Pull request merged**
