### PR TITLE
Added the implementation of Fenwick Tree in Python

### PR DESCRIPTION
**Pull request by Kapersky1337**

### CODE REVIEW

**Comment by Kanhakhatri065** [comment]
can you make an object-oriented version of Fenwick tree?

**Comment by Kapersky1337** [comment]
I will add another version, this provides a clear explanation as well. Please merge this one, I'll add more with time.

**Comment by Kanhakhatri065** [comment]
PR merged

**Comment by Kapersky1337** [comment]
Hello, as per the updated rules, please do add the hacktoberfest-accepted and hacktoberfest labels in this PR, thank you

**Comment by Kapersky1337** [comment]
@Kanhakhatri065 Please do the needful, add the labels.

**Pull request merged**
