### PR TITLE
Fibonacci implementation js

### PR DESCRIPTION
**Pull request by swastikchugh**
Issue #15 Implementation of Fibonacci in JS

### CODE REVIEW

**Comment by ephremdeme** [comment]
improve performance using array

**Comment by swastikchugh** [comment]
array is being used currently, im generating an initial array on line 6 and then pushing subsequent elements to it on line 13

**Comment by ephremdeme** [comment]
don't push just add them like this arr[i] = arr[i-1] + arr[i-2]

**Comment by swastikchugh** [comment]
updated please check

**Comment by swastikchugh** [comment]
Hey @ephremdeme please check

**Comment by ephremdeme** [comment]
@all-contributors please add @swastikchugh  for code

**Comment by ephremdeme** [comment]
Check your profile in the contributors list of faces.

**Comment by swastikchugh** [comment]
Thanks you so much @ephremdeme

**Comment by ephremdeme** [comment]
no problem at all.

**Pull request merged**
