### PR TITLE
Implemented recursive fibonacci

### PR DESCRIPTION
**Pull request by phistav**
Implemented recursive fibonacci.

### CODE REVIEW

**Comment by phistav** [comment]
Hi @Kanhakhatri065 . Could you please the label hacktoberfest-accepted to the PR?

**Comment by phistav** [comment]
> Hi @Kanhakhatri065 . Could you please the label hacktoberfest-accepted to the PR?

Hey @Kanhakhatri065. You have merged the PR but could you also add hacktoberfest-accepted?

**Comment by Kanhakhatri065** [comment]
Done.

**Comment by phistav** [comment]
> Done.

Thanks.

**Pull request merged**
