### PR TITLE
TRIE ds in c++

### PR DESCRIPTION
**Pull request by mnb27**
- Implementation of Trie
- Prefix tree using Trie
- Auto complete feature using Trie

### CODE REVIEW

**Comment by mnb27** [comment]
Fully tested code !!

**Comment by ephremdeme** [comment]
@all-contributors please add @mnb27  for code, ideas

**Comment by mnb27** [comment]
Please add "Hactoberfest-accepted" label to this PR. Kindly look into it. @Kanhakhatri065 @ephremdeme

**Comment by Kanhakhatri065** [comment]
Done.

**Pull request merged**
